version = 0.1

[default.global.parameters]
stack_name = "event-pusher"
region = "us-east-1"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "event-pusher"
parameter_overrides = "DefaultEventTitle=\"Ocupado\" DefaultTimezone=\"America/Sao_Paulo\" MaxDurationHours=\"8\" MinDurationMinutes=\"5\" MaxFutureDays=\"365\" AllowPastEvents=\"false\" ThrottlingBurstLimit=\"2\" ThrottlingRateLimit=\"1\" DailyQuotaLimit=\"20\" GoogleSecretName=\"/event-pusher/google-credentials\""
image_repositories = []

[default.validate.parameters]
lint = true
